Xplique v0.4.2
deel-ai/xplique pull request #118
Opened 2022-11-02 12:57 UTC by fel-thomas

Rebase develop into master.

This PR includes:

#114 fix a missing module in the init of plot.
#115 which enhance documentation and smoothgrad batching mechanism.
#117 which fix a bug in the plot module and another one concerning the miniature of the feature viz.

I will push the v0.4.2 on pypi this afternoon. 
Congrats everyone (@TeodorChiaburu, @AntoninPoche, @lucashervier) 🎉

2022-11-02 13:13 UTC, lucashervier requested changes
Nice PR! There is some minor typo (or english) mistakes that is why I request change (otherwise it would be forgotten) but it is great work!

2022-11-02 13:13 UTC, lucashervier commented on docs/api/attributions/deconvnet.md
> +Deconvnet is one the first attribution method and was proposed in 2013.
is one "of"

2022-11-02 13:13 UTC, lucashervier commented on docs/api/attributions/grad_cam.md
> +Network (CNN) which uses both gradients and the feature maps of the last conv layer.
I think it was better better before (convolutional instead of conv)

2022-11-02 13:13 UTC, lucashervier commented on docs/api/attributions/grad_cam_pp.md
> +Network (CNN) which uses both gradients and the feature maps of the last conv layer.
Idem

2022-11-02 13:13 UTC, lucashervier commented on docs/api/attributions/guided_backpropagation.md
> +Guided-backprop is one the first attribution method and was proposed in 2014.
Guided backpropagation is one of the first (we are writing full sentences I think it is better to not use shortcut for words)

2022-11-02 13:13 UTC, lucashervier commented on xplique/attributions/square_grad.py
> +        return tf.math.reduce_mean(gradients**2, axis=1)
Good catch

2022-11-04 20:04 UTC, fel-thomas commented
Done, thx @lucashervier ;) !
I kept the old description as suggested but fixed the typo.

2022-11-07 10:12 UTC, lucashervier approved these changes
Well done, thx for the changes!

2022-11-07 10:27 UTC, merged