Object Detection & Semantic Segmentation
deel-ai/xplique pull request #136
Opened 2023-09-13 15:18 UTC by AntoninPoche

# Tutorials are in finalization, they will be updated, but links should work

However, through this PR, I discovered that the Regression and Tabular tutorial was quite old and does not use the operator API. Should it be modified before this PR is accepted?

Furthermore, the `operator` is not specified in Classification tutorials but I think it should be for clarity. What do you think?

# Features

## Adapt code to adopt new features

New operators will be added, hence, to clarify the code, operators and the relative operations were divided between `operators.py` and `operators_operations` in 30edc86bfe8c7536477a2915610498bc1456a18d. Naturally, the corresponding tests were adapted in 6914b0cc96fcd10ce61d9569c62a2ff64541fa43.

## Semantic Segmentation

```python
explainer = Method(model, explainer="semantic segmentation")
```

After long debates, with several persons on the team, we agreed on what we may want to explain in semantic segmentation and the relative functions to explain. All those functions were merged into the new `semantic_segmentation_operator` proposed in 150c0448e9560c50b91ba865acf997a5ad9a67d5 and tested in 75c6af43be4bf8f69919356a90bec979b9deda98. It supports perturbation-based and gradient-based methods. Furthermore, the [semantic segmentation tutorial](https://colab.research.google.com/drive/1AHg7KO1fCOX5nZLGZfxkZ2-DLPPdSfbX#scrollTo=jcg2e4QUA7-N) is on a pytorch model, thus, it is compatible with the `TorchWrapper`.

Furthermore, for this operator, the `targets` parameter is complicated to design, therefore, a set of functions was necessary. They were placed in `segmentation.py` in a new `utils_functions/` directory in 26cf99342b7c3e0f3da551b1eb2ff565e0fe9214, with the corresponding tests in 279c217ef0b4de3fdbeb679dbf2a7c65921fc55c, and the documentation integrated to semantic segmentation documentation page.

## Object Detection

```python
explainer = Method(model, explainer="object detection")
```

Following Semantic Segmentation, a new operator: `object_detection_operator` was introduced in 150c0448e9560c50b91ba865acf997a5ad9a67d5 and tested in 75c6af43be4bf8f69919356a90bec979b9deda98. It also supports perturbation-based, gradient-based methods, and the `TorchWrapper` as shown in the [object detection tutorial](https://colab.research.google.com/drive/1X3Yq7BduMKqTA0XEheoVIpOo3IvOrzWL).

Some functions used by the `object_detection_operator` were initially in the `attributions/object_detector.py` file and moved to the `utils_functions/object_detection.py` file in 26cf99342b7c3e0f3da551b1eb2ff565e0fe9214 and tested in 279c217ef0b4de3fdbeb679dbf2a7c65921fc55c. It was moved because the `attributions/object_detector.py` file should depend on `operators.py` and not the opposite. Furthermore, `attributions/object_detector.py` will be removed in future versions, see next section.

Note that a feature was requested: "We should be able to explain the different part of an object detection prediction (*i.e.* box position, proba, ad class". This feature was added and can be specified by adding either `" box position"`, `" box proba"`, or `" box class"` to the initial `"object detection"` value of the `operator` parameter.

## `BoundingBoxExplainer ` is now deprecated

The initial way to apply Xplique to object detection was to use the `BoundingBoxExplainer ` wrapper. However, with the API update, it was natural for the object detection API to match. Furthermore, no documentation was made previously, therefore `BoundingBoxExplainer ` is now deprecated through adb0e82164fbefa2399cc2f29465c0111a2ad366. Nonetheless, the new implementation of this class is just a call to the `object_detection_operator` which was tested in a063d332895d93913a358e76960096aec3a5bd58.

Finally, this is the first case of deprecation in Xplique, the choice was made to use the `deprecated` library which adds a dependency. This choice can be discussed, but this was the only one tested that showed the indicated deprecation warning message. This was added in 6f3bb1a56060a2dc0a8f837a71120c9c3804da26.

# Documentation

## Merge model, operator, and API description page into one

First, the `docs/` directory architecture did not match the documentation architecture, it was confusing for me, hence I modified `docs/` to match the documentation architecture in 5e3ac767a3413e303609aebf5024589bf9ed6019.

As @fel-thomas highlighted in #132 remarks, the documentation was too divided, furthermore, a lot of information was redundant between those pages and they were interdependent. Hence the choice was made to merge the model, operator, and API description page into one in ac09a4b155bd19a296185679b4498d16b2e3e98a.

## Create task related pages

Two tasks (Object Detection and Semantic Segmentation) were introduced in the documentation, their complexity induced a specific documentation page. However, it was not consistent to have documentation pages only for those two tasks. Therefore information about Classification and regression was extracted from the common API page to create two other new task-specific pages. Finally, four task-specific were introduced to the documentation in d7fe19a8343116bd794e1d9b8b67ec95568416b4.

## Adapt other documentation files to changes

Finally, other documentation files were adapted to the new documentation links in 882e2f2484f8fa7ae093a5638e07b96f56b44b99. On those files, the choice was made to add the operator specification in all snippets of code related to attribution methods. It may seem heavy but I think it improves clarity.

2023-09-18 10:15 UTC, AntoninPoche commented on README.md
> -All the attributions method presented below handle both **Classification** and **Regression** tasks.
This table does not appear correctly in the readme.

2023-09-20 09:31 UTC, AntoninPoche commented on README.md
> +    TF : Tensorflow compatible
Replace task acronyms here.

2023-09-29 16:03 UTC, Agustin-Picard requested changes
Awesome work! 🔥 Documentation is quite thorough and I like the way the operators are extended to object detection and segmentation. Comments are mostly typos and ways to improve the clarity of the explanations, but it really shoudn't take long to resolve them ;)

2023-10-03 13:23 UTC, AntoninPoche commented on TUTORIALS.md
> +| Metrics: With Pytorch's model          | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/16bEmYXzLEkUWLRInPU17QsodAIbjdhGP) |
I chose PyTorch.

2023-10-03 14:20 UTC, AntoninPoche commented on docs/api/attributions/object_detection.md
> +To explain each bounding box individually, the images need to be repeated. Indeed, object detector predict several bounding boxes per image and the first dimension of `inputs` and `targets` should ma
Yes it is if you want to explain all the bounding boxes predicted. But you may not want to.

There is a possible optimization for this, but its integration in Xplique is really complex and would require many changes.

2023-10-03 14:23 UTC, AntoninPoche commented on docs/api/attributions/object_detection.md
> +The default intersection score is IOU, but it is possible to define a custom intersection score. The only constraint is that it should follow `xplique.commons.object_detection_operator._box_iou` sign
It may be interesting to choose a score that matches what the model was trained on.

2023-10-03 14:35 UTC, AntoninPoche commented on docs/api/attributions/semantic_segmentation.md
> +This function uses two borders computed via the previous function and limit the zone of interest to the common part between both zone of interest. Class of interest are merged and there are thus two
enables no?

2023-10-03 14:41 UTC, AntoninPoche commented on docs/api/attributions/semantic_segmentation.md
> +A part of an object can be the leg of a person, the head of a dog, or a person in a group of person. This is interesting when the part and the object have been classified differently by the model. It
I am not sure about this one.

2023-10-03 14:50 UTC, AntoninPoche commented on xplique/utils_functions/object_detection.py
> +def _format_objects(predictions: tf.Tensor) -> Tuple[tf.Tensor, tf.Tensor, tf.Tensor]:
Everything in the library is in the [xmin, ymin, xmax, ymax] format to my knowledge.

2023-10-03 14:59 UTC, AntoninPoche commented on docs/api/attributions/object_detection.md
> +To explain each bounding box individually, the images need to be repeated. Indeed, object detector predict several bounding boxes per image and the first dimension of `inputs` and `targets` should ma
Add warning.

2023-10-04 07:36 UTC, AntoninPoche commented on docs/api/attributions/regression.md
> +The regression operator computes the mean absolute error between model's predictions and `targets`.
To change.

2023-10-04 07:37 UTC, AntoninPoche commented on xplique/commons/operators_operations.py
> +    REGRESSION = regression_operator
To change.

2023-10-04 14:47 UTC, Agustin-Picard approved these changes
LGTM. Again, awesome work!

2023-10-05 10:17 UTC, merged