Cockatiel
deel-ai/xplique pull request #149
Opened 2023-11-27 18:39 UTC by fredericboisnard

First PR about the integration of Cockatiel in Xplique.

2024-02-22 10:56 UTC, fredericboisnard commented
The conflicts must come from the 1st patch "test moving the EPSILON & similar to free some RAM" -> I will remove it from the PR since it was mostly to try to improve RAM management on my side (not sure if we want to take it ; and if yes, then it would be better in another PR I suppose)

2024-03-19 16:52 UTC, AntoninPoche requested changes
I only read part of the PR for now. We will have to discuss the architecture of the code. It seem that cockatiel forces us to introduce nlp attributions.

2024-03-19 16:52 UTC, AntoninPoche commented on xplique/commons/nlp.py
> +            sentence = '.'.join(sentence)
Same remark.

2024-03-19 16:52 UTC, AntoninPoche commented on xplique/commons/nlp.py
> +        raise ValueError("Extraction function can be only 'clause', \
You did not include `"flaire_clause"` and `"spacy_clause"` in the error message, but you left `"clause"` which is not a possibility.

2024-03-19 16:52 UTC, AntoninPoche commented on xplique/commons/nlp.py
> +    def get_extractor(extract_fct="sentence", tagger=None, pipeline=None, clause_type=None):
I think that `language` should be an argument of this function.

2024-03-19 16:52 UTC, AntoninPoche commented on xplique/commons/operators.py
> -from ..utils_functions.object_detection import _box_iou, _format_objects, _EPSILON
I agree that the epsilon should not be loaded simultaneously as loading operators. But is it a good thing to initialize it at each run of the tf function?

2024-03-19 16:52 UTC, AntoninPoche commented on xplique/commons/torch_operations.py
> +        The tokenizer function to be used for tokenization. It must be
This description needs to be clarified as no model is defined here. Does this correspond to what you define in the nlp_commons?

If it corresponds to the tokenizer-model pair, as in HuggingFace, then I recommend having a class that treats them both at the same time. It is easier to understand and the API would be more natural.

2024-03-19 16:52 UTC, AntoninPoche commented on xplique/commons/torch_operations.py
> +class NlpPreprocessor(ABC):
This class is called NLP... Should it not be in the nlp commons?

2024-03-20 14:32 UTC, AntoninPoche requested changes
Great work Fred, this is a huge PR! A complex one at that, which raises several points where we should all agree before merging. I listed several general remarks:
- No description of the PR in general, it can be great to clarify your choices and what you are trying to do.
- No notebook or tutorials, I cannot review the plot function or the API without examples. Furthermore, it will be necessary for the final version.
- I cannot launch the tests (from github), I think it is because of the conflicts.
- You did not base your code on the last version of master (1.3.3), I think that the problems you have with memory were solve with last pull requests. It should solve the conflicts at the same time.
- You did not make the documentation, it might be better to discuss the choice made before making it. It will save you some time.
- You remade a lot of indentations (automatically I think), but it created many weird code parts. The line limit is 100 in Xplique.
- We will have to discuss two choices:
    - Where do we put the the nlp parts. In my view a xplique.npl module is pertinent
    - The structure of the code (multi-inheritance)
- The code you added introduced a lot of dependences to other libraries (flair, nltk, transformers (for tests)), we should discuss how to treat this. Maybe have an additionnal nlp_requirements.txt file to install when calling xplique.nlp?

2024-03-20 14:32 UTC, AntoninPoche commented on tests/concepts/test_cockatiel.py
> +    best_sentences_per_concept = cockatiel_explainer_pos.get_best_excerpts_per_concept(
How can you be sure of which sentence will correspond to which concept?

2024-03-21 15:04 UTC, fredericboisnard commented on xplique/concepts/cockatiel.py
> +            preprocessor: NlpPreprocessor,
Yes I understand your concern ; it's possible, but one of the goals of the NlpPreprocessor is to gather both the tokenizer and its parameters in one place, in order to 'proxy' the calls to the tokenizer. Then we can use this feature in cockatiel but also in external parts such as nlp_batch_predict():
- cockatiel._latent_predict() calls self.preprocessor.tokenize(), which will pass the good arguments to the tokenizer
- in torch_operations.nlp_batch_predict(preprocessor): we use preprocessor.preprocess() which again calls preprocessor.tokenize() to pass the good arguments to the tokenizer

If we pass the tokenizer alone in cockatiel.init(), then we will have to provide a variable number of parameters in addition (tokenizer arguments, can vary fron one tokenizer to another), and duplicate these parameters in nlp_batch_predict() :/

Or perhaps there is a better / easier way to implements this ?

Maybe I should rename the NlpPreprocessor into something like TokenizerHelper to better show it's simply to encapsulate tokenizer calls ?

2026-08-28 09:54 UTC, Agustin-Picard commented
Closing because stale.

COCKATIEL was implemented in the [Interpreto](https://github.com/FOR-sight-ai/interpreto) library.

2026-08-28 09:54 UTC, closed without merging